Repository modernui-io/modernuiweb, pull requests merged in 2024-05, with the labels that each got.

#9 Remove next-env from git ignore
  .gitignore
  .prettierignore
  next-env.d.ts
Labels: enhancement, configuration changes

#12 Update primary color
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.css
  .storybook/preview.ts
  src/components/ui/button.tsx
  src/styles/globals.css
Labels: enhancement, Review effort [1-5]: 2

#13 refactor(advanced-tables) Match with original components
  src/components/sections/application-ui/advanced-tables/comparison.tsx
  src/components/sections/application-ui/advanced-tables/default.tsx
  src/components/sections/application-ui/advanced-tables/expandable-rows.tsx
  src/components/sections/application-ui/advanced-tables/products.tsx
  src/components/sections/application-ui/advanced-tables/project-management.tsx
  src/components/sections/application-ui/advanced-tables/sortable-rows.tsx
  src/components/sections/application-ui/advanced-tables/user-management.tsx
Labels: enhancement, Review effort [1-5]: 3

#14 refactor(application-shells) Match with original components
  src/components/sections/application-ui/application-shells/collapsible-sidebar.tsx
  src/components/sections/application-ui/application-shells/double-sidebar.tsx
  src/components/sections/application-ui/application-shells/e-commerce.tsx
  src/components/sections/application-ui/application-shells/sidebar-navbar.tsx
  src/components/sections/application-ui/application-shells/stacked-multiple.tsx
  src/components/sections/application-ui/application-shells/tabs-navbar.tsx
  src/components/sections/application-ui/application-shells/user-profile-sidebar.tsx
Labels: enhancement, Review effort [1-5]: 4, bug fix

#16 refactor(sections) Match delete-confirm, dropdown-filters, and read-m…
  src/components/sections/application-ui/delete-confirm/alert.tsx
  src/components/sections/application-ui/delete-confirm/icon.tsx
  src/components/sections/application-ui/dropdown-filters/advanced-keywords.tsx
  src/components/sections/application-ui/dropdown-filters/properties.tsx
  src/components/sections/application-ui/read-modals/advanced-event.tsx
  src/components/sections/application-ui/read-modals/advanced-user.tsx
  src/components/sections/application-ui/read-modals/default.tsx
  src/components/sections/application-ui/read-modals/event.tsx
  src/components/sections/application-ui/read-modals/product.tsx
  src/components/sections/application-ui/read-modals/user.tsx
Labels: enhancement, Review effort [1-5]: 2
