Repository modernui-io/modernuiweb, pull requests merged in 2024-06, with the labels that each got.

#17 refactor(application-ui) Match read-sections, side-navigations, table…
  src/components/sections/application-ui/read-sections/advanced-event.tsx
  src/components/sections/application-ui/read-sections/advanced-user.tsx
  src/components/sections/application-ui/read-sections/default.tsx
  src/components/sections/application-ui/read-sections/event.tsx
  src/components/sections/application-ui/read-sections/product-carousel.tsx
  src/components/sections/application-ui/read-sections/user.tsx
  src/components/sections/application-ui/side-navigations/alert.tsx
  src/components/sections/application-ui/side-navigations/contacts.tsx
  src/components/sections/application-ui/side-navigations/crypto.tsx
  src/components/sections/application-ui/side-navigations/double.tsx
  src/components/sections/application-ui/side-navigations/secondary.tsx
  src/components/sections/application-ui/side-navigations/tasks-double.tsx
  src/components/sections/application-ui/side-navigations/user-profile.tsx
  src/components/sections/application-ui/table-headers/breadcrumb.tsx
  src/components/sections/application-ui/table-headers/button-group-filters.tsx
  src/components/sections/application-ui/table-headers/comparison.tsx
  src/components/sections/application-ui/table-headers/cta-button-group.tsx
  src/components/sections/application-ui/table-headers/date-range-picker.tsx
  src/components/sections/application-ui/table-headers/default.tsx
  src/components/sections/application-ui/table-headers/multi-level-filters.tsx
  src/components/sections/application-ui/table-headers/search-input.tsx
  src/components/sections/application-ui/table-headers/settings.tsx
  src/components/sections/application-ui/table-headers/statistics.tsx
  src/components/sections/application-ui/table-headers/tooltip-select-filters.tsx
  src/components/sections/application-ui/update-modals/accordion.tsx
  src/components/sections/application-ui/update-modals/advanced-event.tsx
  src/components/sections/application-ui/update-modals/default.tsx
  src/components/sections/application-ui/update-modals/event.tsx
  src/components/sections/application-ui/update-modals/product.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#15 refactor(sections) match create-modals, dashboard-footers, and dashbo…
  src/components/sections/application-ui/create-modals/advanced-event.tsx
  src/components/sections/application-ui/create-modals/advanced-user.tsx
  src/components/sections/application-ui/create-modals/event.tsx
  src/components/sections/application-ui/create-modals/product.tsx
  src/components/sections/application-ui/dashboard-footers/default.tsx
  src/components/sections/application-ui/dashboard-footers/language-selector.tsx
  src/components/sections/application-ui/dashboard-footers/pagination.tsx
  src/components/sections/application-ui/dashboard-navbars/centered-cta-search.tsx
  src/components/sections/application-ui/dashboard-navbars/cta-search.tsx
  src/components/sections/application-ui/dashboard-navbars/default.tsx
  src/components/sections/application-ui/dashboard-navbars/project-dropdown.tsx
  src/components/sections/application-ui/dashboard-navbars/project-switch-subnav.tsx
  src/components/sections/application-ui/dashboard-navbars/search-input.tsx
Labels: enhancement, Review effort [1-5]: 4, bug fix

#10 Feature/comment section
  .storybook/main.ts
  pnpm-lock.yaml
  src/components/sections/application-ui/dropdown-filters/advanced-keywords.tsx
  src/components/sections/publisher-ui/comment-section/comment-upvotes.tsx
  src/components/sections/publisher-ui/comment-section/default.tsx
  src/components/sections/publisher-ui/comment-section/solid-background.tsx
  src/components/sections/publisher-ui/comment-section/stories/comment-upvotes.stories.tsx
  src/components/sections/publisher-ui/comment-section/stories/default.stories.tsx
  src/components/sections/publisher-ui/comment-section/stories/solid-background.stories.tsx
  src/components/sections/publisher-ui/comment-section/stories/wordpress-comments.stories.tsx
  src/components/sections/publisher-ui/comment-section/wordpress-comments.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4

#19 Feature/Blog publisher UI
  src/components/sections/publisher-ui/blog-template/Feature-article.tsx
  src/components/sections/publisher-ui/blog-template/background-image.tsx
  src/components/sections/publisher-ui/blog-template/community-blog.tsx
  src/components/sections/publisher-ui/blog-template/default-blog.tsx
  src/components/sections/publisher-ui/blog-template/live-blogging.tsx
  src/components/sections/publisher-ui/blog-template/right-sidebar.tsx
  src/components/sections/publisher-ui/blog-template/stories/background-Image.stories.tsx
  src/components/sections/publisher-ui/blog-template/stories/community-blog.stories.tsx
  src/components/sections/publisher-ui/blog-template/stories/default.stories.tsx
  src/components/sections/publisher-ui/blog-template/stories/feature-article.stories.tsx
  src/components/sections/publisher-ui/blog-template/stories/live-blogging.stories.tsx
  src/components/sections/publisher-ui/blog-template/stories/right-sidebar.stories.tsx
  src/lib/assets/images/background.png
  src/lib/assets/images/blog-1 .png
  src/lib/assets/images/profile-picture-2.jpg
  src/lib/assets/images/profile-picture-3.jpg
  src/lib/assets/images/profile-picture-4.jpg
  src/lib/assets/images/profile-picture-5.jpg
  src/lib/assets/images/typography-image-1.png
  src/lib/assets/images/typography-image-2.png
Labels: documentation, enhancement, Review effort [1-5]: 5

#20 Feature/ cart components
  src/components/sections/e-commerce-ui/shopping-cart/default.tsx
  src/components/sections/e-commerce-ui/shopping-cart/drawer.tsx
  src/components/sections/e-commerce-ui/shopping-cart/modal.tsx
  src/components/sections/e-commerce-ui/shopping-cart/sidebar.tsx
  src/components/sections/e-commerce-ui/shopping-cart/stories/default.stories.tsx
  src/components/sections/e-commerce-ui/shopping-cart/stories/drawer.stories.tsx
  src/components/sections/e-commerce-ui/shopping-cart/stories/modal.stories.tsx
  src/components/sections/e-commerce-ui/shopping-cart/stories/sidebar.stories.tsx
  src/components/sections/e-commerce-ui/shopping-cart/stories/table.stories.tsx
  src/components/sections/e-commerce-ui/shopping-cart/table.tsx
  src/lib/assets/images/apple-watch-dark.svg
  src/lib/assets/images/apple-watch-light.svg
  src/lib/assets/images/background.png
  src/lib/assets/images/blog-1 .png
  src/lib/assets/images/imac-back-dark.svg
  src/lib/assets/images/imac-back.svg
  src/lib/assets/images/imac-front-dark.svg
  src/lib/assets/images/imac-front.svg
  src/lib/assets/images/imac-showcase-dark.svg
  src/lib/assets/images/imac-showcase.svg
  src/lib/assets/images/imac-side-dark.svg
  src/lib/assets/images/imac-side.svg
  src/lib/assets/images/ipad-dark.svg
  src/lib/assets/images/ipad-light.svg
  src/lib/assets/images/iphone-dark.svg
  src/lib/assets/images/iphone-light.svg
  src/lib/assets/images/macbook-pro-dark.svg
  src/lib/assets/images/macbook-pro-light.svg
  src/lib/assets/images/profile-picture-2.jpg
  src/lib/assets/images/profile-picture-3.jpg
  src/lib/assets/images/profile-picture-4.jpg
  src/lib/assets/images/profile-picture-5.jpg
  src/lib/assets/images/ps5-dark.svg
  src/lib/assets/images/ps5-light.svg
  src/lib/assets/images/typography-image-1.png
  src/lib/assets/images/typography-image-2.png
  src/lib/assets/images/xbox-dark.svg
  src/lib/assets/images/xbox-light.svg
Labels: enhancement, Tests, Review effort [1-5]: 4

#21 Marketing UI - Team Section
  src/components/sections/marketing-ui/team-sections/card-with-grid-layout-cta.tsx
  src/components/sections/marketing-ui/team-sections/carousel-slider.tsx
  src/components/sections/marketing-ui/team-sections/four-col-grid-social-cta.tsx
  src/components/sections/marketing-ui/team-sections/general-description-with-team-members.tsx
  src/components/sections/marketing-ui/team-sections/grid-layout-cards.tsx
  src/components/sections/marketing-ui/team-sections/grid-layout-clean.tsx
  src/components/sections/marketing-ui/team-sections/overlay-cards-with-zoom-effect.tsx
  src/components/sections/marketing-ui/team-sections/stories/card-with-grid-layout-cta.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/carousel-slider.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/four-col-grid-social-cta.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/general-description-with-team-members.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/grid-layout-cards.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/grid-layout-clean.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/overlay-cards-with-zoom-effect.stories.tsx
  src/components/sections/marketing-ui/team-sections/stories/team-member-cards.stories.tsx
  src/components/sections/marketing-ui/team-sections/team-member-cards.tsx
  src/lib/assets/images/bonnie-green.png
  src/lib/assets/images/content-team-11.png
  src/lib/assets/images/content-team-12.png
  src/lib/assets/images/content-team-13.png
  src/lib/assets/images/content-team-14.png
  src/lib/assets/images/content-team-3.png
  src/lib/assets/images/content-team-4.png
  src/lib/assets/images/content-team-5.png
  src/lib/assets/images/helene-engels.png
  src/lib/assets/images/jese-leos.png
  src/lib/assets/images/joseph-mcfall.png
  src/lib/assets/images/lana-byrd.png
  src/lib/assets/images/member-1.png
  src/lib/assets/images/member-2.png
  src/lib/assets/images/member-3.png
  src/lib/assets/images/member-6.png
  src/lib/assets/images/michael-gouch.png
  src/lib/assets/images/neil-sims.png
  src/lib/assets/images/roberta-casas.png
  src/lib/assets/images/sofia-mcguire.png
  src/lib/assets/images/thom-belly.png
  src/lib/assets/images/thomas-lean.png
  src/lib/assets/images/thomas-lean_files/bonnie-green.png
  src/lib/assets/images/thomas-lean_files/joseph-mcfall.png
  src/lib/assets/images/thomas-lean_files/member-1.png
  src/lib/assets/images/thomas-lean_files/sofia-mcguire.png
Labels: enhancement, Tests, Review effort [1-5]: 4

#24 Marketing UI - Social Proofs
  src/components/sections/marketing-ui/social-proofs/cards-with-statistics.tsx
  src/components/sections/marketing-ui/social-proofs/carousel-slider.tsx
  src/components/sections/marketing-ui/social-proofs/heading-with-statistics.tsx
  src/components/sections/marketing-ui/social-proofs/illustration-with-statistics.tsx
  src/components/sections/marketing-ui/social-proofs/social-proof-default.tsx
  src/components/sections/marketing-ui/social-proofs/statistics-with-icons-and-cta.tsx
  src/components/sections/marketing-ui/social-proofs/stories/cards-with-statistics.stories.tsx
  src/components/sections/marketing-ui/social-proofs/stories/carousel-slider.stories.tsx
  src/components/sections/marketing-ui/social-proofs/stories/heading-with-statistics.stories.tsx
  src/components/sections/marketing-ui/social-proofs/stories/illustation-with-statistics.stories.tsx
  src/components/sections/marketing-ui/social-proofs/stories/social-proof-default.stories.tsx
  src/components/sections/marketing-ui/social-proofs/stories/statistics-with-icons-and-cta.stories.tsx
  src/lib/assets/images/conference.png
  src/lib/assets/images/girl-with-phone.png
  src/lib/assets/images/man-at-office.png
  src/lib/assets/images/meeting.png
  src/lib/assets/images/office-work.png
  src/lib/assets/images/office.png
  src/lib/assets/images/table-professor.png
  src/lib/assets/images/work-from-home.png
  src/lib/assets/images/workspace.png
Labels: enhancement, Tests, Review effort [1-5]: 4

#23 Marketing UI - Pricing Tables
  src/components/sections/marketing-ui/pricing-tables/comparison-table.tsx
  src/components/sections/marketing-ui/pricing-tables/default-pricing-cards.tsx
  src/components/sections/marketing-ui/pricing-tables/feature-list-description-price.tsx
  src/components/sections/marketing-ui/pricing-tables/highlighted-pricing-plan.tsx
  src/components/sections/marketing-ui/pricing-tables/horizontal-pricing-cards.tsx
  src/components/sections/marketing-ui/pricing-tables/pricing-plan-with-toggle-switch.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/comparison-table.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/default-pricing-cards.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/feature-list-description-price.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/highlighted-pricing-plan.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/horizontal-pricing-cards.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/pricing-plan-with-toggle-switch.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/stories/tabs-selector-pricing-cards.stories.tsx
  src/components/sections/marketing-ui/pricing-tables/tabs-selector-pricing-cards.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4

#29 feat(application-ui) Add CRUD Layouts section
  src/components/sections/application-ui/crud-layouts/default.tsx
  src/components/sections/application-ui/crud-layouts/expandable-rows.tsx
  src/components/sections/application-ui/crud-layouts/horizontal-cards.tsx
  src/components/sections/application-ui/crud-layouts/product-management.tsx
  src/components/sections/application-ui/crud-layouts/stories/default.stories.tsx
  src/components/sections/application-ui/crud-layouts/stories/expandable-rows.stories.tsx
  src/components/sections/application-ui/crud-layouts/stories/horizontal-cards.stories.tsx
  src/components/sections/application-ui/crud-layouts/stories/product-management.stories.tsx
  src/components/sections/application-ui/crud-layouts/stories/user-management.stories.tsx
  src/components/sections/application-ui/crud-layouts/user-management.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4

#30 Markerting UI - Register Form
  src/components/sections/marketing-ui/register-forms/auth-register-forms.tsx
  src/components/sections/marketing-ui/register-forms/default-register-forms.tsx
  src/components/sections/marketing-ui/register-forms/illustration-register-form.tsx
  src/components/sections/marketing-ui/register-forms/stories/auth-register-forms.stories.tsx
  src/components/sections/marketing-ui/register-forms/stories/default-register-forms.stories.tsx
  src/components/sections/marketing-ui/register-forms/stories/illustration-register-form.stories.tsx
  src/lib/assets/images/register-ilustration.svg
Labels: enhancement, Tests, Review effort [1-5]: 4

#28 Marketing UI - Contact Forms
  src/components/sections/marketing-ui/contact-forms/address-location-contact-form.tsx
  src/components/sections/marketing-ui/contact-forms/background-image-contact-form.tsx
  src/components/sections/marketing-ui/contact-forms/company-info-contact-form.tsx
  src/components/sections/marketing-ui/contact-forms/default-contact-forms.tsx
  src/components/sections/marketing-ui/contact-forms/help-centre-contact-form.tsx
  src/components/sections/marketing-ui/contact-forms/links-contact-form.tsx
  src/components/sections/marketing-ui/contact-forms/stories/address-location-contact-form.stories.tsx
  src/components/sections/marketing-ui/contact-forms/stories/background-image-contact-form.stories.tsx
  src/components/sections/marketing-ui/contact-forms/stories/company-info-contact-form.stories.tsx
  src/components/sections/marketing-ui/contact-forms/stories/default-contact-forms.stories.tsx
  src/components/sections/marketing-ui/contact-forms/stories/help-centre-contact-form.stories.tsx
  src/components/sections/marketing-ui/contact-forms/stories/links.contaxt-form.stories.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4, address PR feedback

#25 Marketing UI - Footer Sections
  src/components/sections/marketing-ui/footer-sections/default-footer-section.tsx
  src/components/sections/marketing-ui/footer-sections/newsletter-sign-up.tsx
  src/components/sections/marketing-ui/footer-sections/original-footer.tsx
  src/components/sections/marketing-ui/footer-sections/prefooter-cta.tsx
  src/components/sections/marketing-ui/footer-sections/sitemap-links.tsx
  src/components/sections/marketing-ui/footer-sections/sitemap_logo_social_media.tsx
  src/components/sections/marketing-ui/footer-sections/social_media-icons.tsx
  src/components/sections/marketing-ui/footer-sections/stories/default-footer-section.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/newsletter-sign-up.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/original-footer.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/pre-footer-cta.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/sitemap-links.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/sitemap_logo_social_media.stories.tsx
  src/components/sections/marketing-ui/footer-sections/stories/social_media-icons.stories.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4, address PR feedback

#33 refactor(application-ui) Matching with original components
  src/components/sections/application-ui/advanced-tables/sortable-rows.tsx
  src/components/sections/application-ui/advanced-tables/user-management.tsx
  src/components/sections/application-ui/application-shells/collapsible-sidebar.tsx
  src/components/sections/application-ui/application-shells/double-sidebar.tsx
  src/components/sections/application-ui/application-shells/sidebar-navbar.tsx
  src/components/sections/application-ui/application-shells/stacked-multiple.tsx
  src/components/sections/application-ui/application-shells/tabs-navbar.tsx
  src/components/sections/application-ui/create-modals/advanced-event.tsx
  src/components/sections/application-ui/create-modals/event.tsx
  src/components/sections/application-ui/dashboard-navbars/centered-cta-search.tsx
  src/components/sections/application-ui/dashboard-navbars/default.tsx
  src/components/sections/application-ui/dashboard-navbars/project-dropdown.tsx
  src/components/sections/application-ui/dashboard-navbars/search-input.tsx
  src/components/sections/application-ui/dropdown-filters/advanced-options.tsx
  src/components/sections/application-ui/side-navigations/alert.tsx
  src/components/sections/application-ui/side-navigations/contacts.tsx
  src/components/sections/application-ui/side-navigations/double.tsx
  src/components/sections/application-ui/side-navigations/projects-team-switch.tsx
  src/components/sections/application-ui/side-navigations/tasks-double.tsx
  src/components/sections/application-ui/table-headers/search-input.tsx
  src/components/sections/application-ui/table-headers/tabs.tsx
  src/components/sections/application-ui/update-modals/advanced-event.tsx
  src/components/sections/application-ui/update-modals/product.tsx
Labels: enhancement, Review effort [1-5]: 3, miscellaneous

#11 Marketing UI - Content Section
  src/components/sections/marketing-ui/content-sections/content-image-card.tsx
  src/components/sections/marketing-ui/content-sections/heading-description-two-col.tsx
  src/components/sections/marketing-ui/content-sections/heading-description.tsx
  src/components/sections/marketing-ui/content-sections/image-gallery.tsx
  src/components/sections/marketing-ui/content-sections/image-heading-description.tsx
  src/components/sections/marketing-ui/content-sections/logo-content-section.tsx
  src/components/sections/marketing-ui/content-sections/social-content.tsx
  src/components/sections/marketing-ui/content-sections/stories/content-image-card.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/heading-description-two-col.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/heading-with-description.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/image-gallery.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/image-heading-secription.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/logo-content-section.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/social-content.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/table-content.stories.tsx
  src/components/sections/marketing-ui/content-sections/stories/video-content.stories.tsx
  src/components/sections/marketing-ui/content-sections/table-content-image.tsx
  src/components/sections/marketing-ui/content-sections/video-content.tsx
  src/lib/assets/images/computer-dark.png
  src/lib/assets/images/content-gallery-1.png
  src/lib/assets/images/content-gallery-2.png
  src/lib/assets/images/content-gallery-3.png
  src/lib/assets/images/content-gallery-4.png
  src/lib/assets/images/content-gallery-5.png
  src/lib/assets/images/content-gallery-6.png
  src/lib/assets/images/office-content-1.png
  src/lib/assets/images/office-content-2.png
  src/lib/assets/images/office-content-3.png
  src/lib/assets/images/office-long-1.png
  src/lib/assets/images/office-long-2.png
Labels: enhancement, Tests, Review effort [1-5]: 3, address PR feedback

#41 fix(main.ts) Remove commenting on all sections, and add comment on th…
  .storybook/main.ts
Labels: Review effort [1-5]: 2, bug fix

#42 Application UI - Update Drawers
  src/components/sections/application-ui/update-drawers/advanced-update-user-drawer.tsx
  src/components/sections/application-ui/update-drawers/stories/advanced-update-user-drawer.stories.tsx
  src/components/sections/application-ui/update-drawers/stories/update-default-drawer.stories.tsx
  src/components/sections/application-ui/update-drawers/stories/update-event-drawer.stories.tsx
  src/components/sections/application-ui/update-drawers/stories/update-product-drawer.stories.tsx
  src/components/sections/application-ui/update-drawers/stories/update-user-drawer.stories.tsx
  src/components/sections/application-ui/update-drawers/update-default-drawer.tsx
  src/components/sections/application-ui/update-drawers/update-event-drawer.tsx
  src/components/sections/application-ui/update-drawers/update-product-drawer.tsx
  src/components/sections/application-ui/update-drawers/update-user-drawer.tsx
  src/lib/assets/images/imac-back-image.png
  src/lib/assets/images/imac-front-image.png
  src/lib/assets/images/imac-side-image.png
Labels: enhancement, Tests, Review effort [1-5]: 4, address PR feedback

#43 Application UI - Create Forms
  src/components/sections/application-ui/create-forms/advanced-create-user-form.tsx
  src/components/sections/application-ui/create-forms/create-event-form.tsx
  src/components/sections/application-ui/create-forms/create-form-accordion.tsx
  src/components/sections/application-ui/create-forms/create-user-form.tsx
  src/components/sections/application-ui/create-forms/default-form.tsx
  src/components/sections/application-ui/create-forms/stories/advanced-create-user-form.stories.tsx
  src/components/sections/application-ui/create-forms/stories/create-event-form.stories.tsx
  src/components/sections/application-ui/create-forms/stories/create-form-accordion.stories.tsx
  src/components/sections/application-ui/create-forms/stories/create-user-form.stories.tsx
  src/components/sections/application-ui/create-forms/stories/default-form.stories.tsx
Labels: enhancement, Tests, Review effort [1-5]: 4, address PR feedback

#45 Application UI - Faceted Search Drawers
  src/components/sections/application-ui/faceted-search-drawers/advanced-faceted-datepicker.tsx
  src/components/sections/application-ui/faceted-search-drawers/default-faceted-search-drawer.tsx
  src/components/sections/application-ui/faceted-search-drawers/faceted-search-accordion.tsx
  src/components/sections/application-ui/faceted-search-drawers/large-faceted-search.tsx
  src/components/sections/application-ui/faceted-search-drawers/stories/advanced-faceted-datepicker.stories.tsx
  src/components/sections/application-ui/faceted-search-drawers/stories/default-faceted-search-drawer.stories.tsx
  src/components/sections/application-ui/faceted-search-drawers/stories/faceted-search-accordion.stories.tsx
  src/components/sections/application-ui/faceted-search-drawers/stories/large-faceted-search.stories.tsx
Labels: Review effort [1-5]: 5

#46 Application UI - Success Message
  src/components/sections/application-ui/success-message/default-success-message.tsx
  src/components/sections/application-ui/success-message/stories/default-success-message.stories.tsx
  src/components/sections/application-ui/success-message/stories/success-message-description.stories.tsx
  src/components/sections/application-ui/success-message/stories/success-message-item-details.stories.tsx
  src/components/sections/application-ui/success-message/stories/success-message-list.stories.tsx
  src/components/sections/application-ui/success-message/stories/success-message-repository.stories.tsx
  src/components/sections/application-ui/success-message/success-message-description.tsx
  src/components/sections/application-ui/success-message/success-message-item-details.tsx
  src/components/sections/application-ui/success-message/success-message-list.tsx
  src/components/sections/application-ui/success-message/success-message-repository.tsx
Labels: Review effort [1-5]: 3, address PR feedback

#47 Application UI - Read Drawers
  src/components/sections/application-ui/read-drawers/advanced-read-event-drawer.tsx
  src/components/sections/application-ui/read-drawers/advanced-read-user-drawer.tsx
  src/components/sections/application-ui/read-drawers/read-default-drawer.tsx
  src/components/sections/application-ui/read-drawers/read-event-drawer.tsx
  src/components/sections/application-ui/read-drawers/read-product-drawer-images.tsx
  src/components/sections/application-ui/read-drawers/read-user-drawer.tsx
  src/components/sections/application-ui/read-drawers/stories/advanced-read-event-drawer.stories.tsx
  src/components/sections/application-ui/read-drawers/stories/advanced-read-user-drawer.stories.tsx
  src/components/sections/application-ui/read-drawers/stories/read-default-drawer.stories.tsx
  src/components/sections/application-ui/read-drawers/stories/read-event-drawer.stories.tsx
  src/components/sections/application-ui/read-drawers/stories/read-product-drawer-images.stories.tsx
  src/components/sections/application-ui/read-drawers/stories/read-user-drawer.stories.tsx
Labels: Review effort [1-5]: 4, address PR feedback

#50 Application UI - Faceted Search Modals
  src/components/sections/application-ui/faceted-search-modals/advanced-search.tsx
  src/components/sections/application-ui/faceted-search-modals/default-search-modal.tsx
  src/components/sections/application-ui/faceted-search-modals/filters-with-tabs.tsx
  src/components/sections/application-ui/faceted-search-modals/search-toggle-filters.tsx
  src/components/sections/application-ui/faceted-search-modals/search-with-datepicker.tsx
  src/components/sections/application-ui/faceted-search-modals/stories/advanced-search.stories.tsx
  src/components/sections/application-ui/faceted-search-modals/stories/default-search-modal.stories.tsx
  src/components/sections/application-ui/faceted-search-modals/stories/filters-with-tabs.stories.tsx
  src/components/sections/application-ui/faceted-search-modals/stories/search-toggle-filters.stories.tsx
  src/components/sections/application-ui/faceted-search-modals/stories/search-with-datepicker.stories.tsx
Labels: Review effort [1-5]: 4, address PR feedback

#49 Marketing UI - Header Sections
  src/components/sections/marketing-ui/header-sections/default-header-navigation.tsx
  src/components/sections/marketing-ui/header-sections/header-with-centered-logo.tsx
  src/components/sections/marketing-ui/header-sections/header-with-dropdown-menu.tsx
  src/components/sections/marketing-ui/header-sections/header-with-mega-dropdown.tsx
  src/components/sections/marketing-ui/header-sections/header-with-mega-menu.tsx
  src/components/sections/marketing-ui/header-sections/header-with-searchbar.tsx
  src/components/sections/marketing-ui/header-sections/header-with-sub-navbar.tsx
  src/components/sections/marketing-ui/header-sections/header-with-user-dropdown.tsx
  src/components/sections/marketing-ui/header-sections/stories/default-header-navigation.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-centered-logo.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-dropdown-menu.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-mega-dropdown.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-mega-menu.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-searchbar.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-sub-navbar.stories.tsx
  src/components/sections/marketing-ui/header-sections/stories/header-with-user-dropdown.stories.tsx
Labels: Review effort [1-5]: 4, address PR feedback
